Moving the custom errors to "errors.py" requires an "import" statement in "callfile.py" before they can be used.
I put the "import" at the top of the file, following Python convention, but it could just as easily be done "just in time", instead. This fixes a NameError bug when attempting the following:

>>> from pycall import CallFile
>>> CallFile(spool_dir = 'something/private/').run()
NameError: global name 'NoSpoolPermissionError' is not defined